clone:
  depth: full # depth defined
options:
  max-time: 45 # pipeline max-time execution set to 45 mins  
definitions:
  steps: 

  ####################### Steps defined to copy file to s3 #######################
    - step: &Copy-file
        image: amazon/aws-cli:2.0.42
        name: Copy-to-s3
        script:
          - if [ -n "$Environment" ] ; then export BITBUCKET_DEPLOYMENT_ENVIRONMENT=$Environment; fi
          - . ./config/config-aws.sh

          - PORTFOLIO=ops
          - POD=data-load
          - echo ${DB_TYPE}
          - echo ${DB}.${SCHEMA,,}.${TABLE,,}
          - echo $YYYYMMDD

          - aws --profile serverless s3 sync files s3://${BITBUCKET_DEPLOYMENT_ENVIRONMENT,,}--${Portfolio,,}-${Pod,,}-bucket/files/${DB_TYPE}/${DB}/${SCHEMA,,}/${TABLE,,}/$YYYYMMDD/


  ####################### Steps defined to delete file(s) from s3 #######################
    - step: &delete-file
        image: amazon/aws-cli:2.0.42
        name: Delete-file
        script:
          - if [ -n "$Environment" ] ; then export BITBUCKET_DEPLOYMENT_ENVIRONMENT=$Environment; fi
          - . ./config/config-aws.sh

          - PORTFOLIO=ops
          - POD=data-load
          - bucket_name=s3://${Environment}-${Portfolio,,}-${Pod,,}-bucket/
          - echo "S3 bucket - ${bucket_name}" 
          - echo ${file_path}
          - echo ${delete_type}

          - if [[ $delete_type == "DRY_RUN" ]]; then 
          - aws --profile serverless s3 rm ${bucket_name} --recursive --dryrun --exclude "*" --include "${file_path}*"

          - elif [[ $delete_type == "DELETE" ]]; then 
          - aws --profile serverless s3 rm ${bucket_name} --recursive --exclude "*" --include "${file_path}*"

          - else
          - echo "do nothing"
          - fi


pipelines:
  custom:
    Copy to S3:
      - variables:
        - name: BITBUCKET_DEPLOYMENT_ENVIRONMENT
          default: development
          allowed-values:
            - evaluation
            - development
            - ftest
            - staging
            - ptest
            - production
        - name: DB_TYPE
          default: oracle
          allowed-values:
            - oracle
            - postgres
        - name: DB
          allowed-values:
            - RAE
            - DW
            - SEC
            - ERAS
            - AMCAS
            - ATS
            - EIS
            - edc
            - eras
            - mcat
            - mda
            - ps
        - name: SCHEMA
        - name: TABLE
        - name: YYYYMMDD
      - step:
          <<: *copy-file
          name: Copy-to-env

    Delete from S3:
      - variables:
        - name: BITBUCKET_DEPLOYMENT_ENVIRONMENT
          default: development
          allowed-values:
            - evaluation
            - development
            - ftest
            - staging
            - ptest
            - production
        - name: file_path
        - name: delete_type
          default: DRY_RUN
          allowed-values:
            - DRY_RUN
            - DELETE
      - step:
          <<: *delete-file
          name: Delete-file




clone:
  depth: full # depth defined
options:
  max-time: 30 # pipeline max-time execution set to 30 mins

definitions:
  steps:
      - step: &Template-Validation
          image: amazon/aws-cli:2.0.42
          name: Template-Validation
          script:
            - aws --profile serverless configure set default.region us-east-1
            - aws --profile serverless configure set aws_access_key_id $DEV_ROLE_USER_ACCESS_KEY
            - aws --profile serverless configure set aws_secret_access_key $DEV_ROLE_USER_SECURITY_KEY
            - aws --profile serverless configure set role_arn $DEV_ROLE_ARN_SERVERLESS
            - aws --profile serverless configure set source_profile serverless
#            - aws --profile serverless cloudformation validate-template --template-body file://data-load-glue.yml

      - step: &Deploy
          image: amazon/aws-cli:2.0.42
          name: Deploy
          script:
            - if [ -n "$Environment" ] ; then export BITBUCKET_DEPLOYMENT_ENVIRONMENT=$Environment; fi
            - . ./config/config-aws.sh
            - echo "${costCenter}"
            - aws --profile serverless s3 cp ./gluejob_data_load.py s3://${BITBUCKET_DEPLOYMENT_ENVIRONMENT}-dst-aws-glue-assets/scripts/ops/data-load/
            - aws --profile serverless cloudformation deploy --template-file ./data-load-glue.yml --stack-name $BITBUCKET_REPO_SLUG-s3bucket --capabilities CAPABILITY_NAMED_IAM  --tags "Business-Unit=dataeng" "CostCenter=${costCenter}" "Project=PJ-IT-2150" --parameter-overrides file://config-${EnvType,,}.json
            - aws --profile serverless cloudformation deploy --template-file ./data-load-glue.yml --stack-name $BITBUCKET_REPO_SLUG --capabilities CAPABILITY_NAMED_IAM  --tags "Business-Unit=dataeng" "CostCenter=${costCenter}" "Project=PJ-IT-2150" --parameter-overrides file://config-${EnvType,,}.json
          after-script:
            - aws --profile serverless cloudformation describe-stack-events --stack-name $BITBUCKET_REPO_SLUG-s3bucket
            - aws --profile serverless cloudformation describe-stack-events --stack-name $BITBUCKET_REPO_SLUG

      - step: &Copy-file
          image: amazon/aws-cli:2.0.42
          name: Copy-to-s3
          script:
            - if [ -n "$Environment" ] ; then export BITBUCKET_DEPLOYMENT_ENVIRONMENT=$Environment; fi
            - . ./config/config-aws.sh
            - aws --profile serverless s3 cp ./gluejob_data_load.py s3://${BITBUCKET_DEPLOYMENT_ENVIRONMENT}-dst-aws-glue-assets/scripts/ops/data-load/



pipelines:
  ###################### Custom pipelines to provision Infra######################
  branches:
    "{main}":
      - step:
          <<: *Template-Validation
          name: Template Validation
      - step:
          <<: *Deploy
          name: Provision stack in evaluation
          deployment: evaluation
          trigger: manual
      - step:
          <<: *Deploy
          name: Provision stack in development
          deployment: development
          trigger: manual
      - step:
          <<: *Deploy
          name: Provision stack in ftest
          deployment: ftest
          trigger: manual
      - step:
          <<: *Deploy
          name: Provision stack in staging
          deployment: staging
          trigger: manual
      - step:
          <<: *Deploy
          name: Provision stack in ptest
          deployment: ptest
          trigger: manual
      - step:
          <<: *Deploy
          name: Provision stack in production
          deployment: production
          trigger: manual

  custom:
    Custom CFT deployment:
      - variables:
        - name: BITBUCKET_DEPLOYMENT_ENVIRONMENT
          default: development
          allowed-values:
            - evaluation
            - development
            - ftest
            - staging
            - ptest
            - production
      - step:
          <<: *Template-Validation
          name: Validate-template
          deployment: evaluation
      - step:
          <<: *Deploy
          name: Deploy-to-env

    Copy script to S3:
      - variables:
        - name: BITBUCKET_DEPLOYMENT_ENVIRONMENT
          default: development
          allowed-values:
            - evaluation
            - development
            - ftest
            - staging
            - ptest
            - production
      - step:
          <<: *Copy-file
          name: Copy-to-env